import{S as m,N as h,K as v,a as g}from"./assets/vendor-D5tVdYkC.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const S="/ChooseMe/assets/icons-DhHkN1_s.svg",E="/ChooseMe/assets/project3-Bf_MJXyh.jpg",L="/ChooseMe/assets/project3@2x-CtqdgkoC.jpg",l=[{title:"Wallet webservice",tech:"React, JavaScript, Node JS, Git",image1x:E,image2x:L,alt:"Wallet webservice",link:"#"},{title:"Green harvest webservice",tech:"React, JavaScript, Node JS, Git",image1x:"./img/project7.jpg",image2x:"./img/project7@2x.jpg",alt:"Green harvest webservice",link:"#"},{title:"English Exellence website",tech:"React, JavaScript, Node JS, Git",image1x:"./img/project5.jpg",image2x:"./img/project5@2x.jpg",alt:"English Exellence website",link:"#"},{title:"PORTFOLIO WEBSITE",tech:"HTML, SCSS, JavaScript",image1x:"./img/project4.jpg",image2x:"./img/project4@2x.jpg",alt:"Portfolio Website",link:"#"},{title:"TRAVEL AGENCY SITE",tech:"React, TypeScript, Tailwind",image1x:"./img/project6.jpg",image2x:"./img/project6@2x.jpg",alt:"Travel Agency Website",link:"#"},{title:"VYSHYVANKA VIBES LANDING PAGE",tech:"HTML, SCSS, JavaScript",image1x:"./img/project2.jpg",image2x:"./img/project2@2x.jpg",alt:"VYSHYVANKA VIBES LANDING PAGE",link:"#"},{title:"POWER PULSE WEBSERVICE",tech:"HTML, SCSS, JavaScript",image1x:"./img/project1.jpg",image2x:"./img/project1@2x.jpg",alt:"POWER PULSE WEBSERVICE",link:"#"},{title:"CHEGO JEWELRY WEBSITE",tech:"HTML, SCSS, JavaScript",image1x:"./img/project8.jpg",image2x:"./img/project8@2x.jpg",alt:"CHEGO JEWELRY WEBSITE",link:"#"},{title:"FRUITBOX ONLINE STORE",tech:"HTML, SCSS, JavaScript",image1x:"./img/project9.jpg",image2x:"./img/project9@2x.jpg",alt:"FRUITBOX ONLINE STORE",link:"#"},{title:"STARLIGHT STUDIO LANDING PAGE",tech:"HTML, SCSS, JavaScript",image1x:"./img/project10.jpg",image2x:"./img/project10@2x.jpg",alt:"STARLIGHT STUDIO LANDING PAGE",link:"#"}];let n=0;const d=3,j=document.getElementById("projectsList"),p=document.getElementById("loadMoreBtn"),f=e=>{const i=document.createElement("li");return i.className="project-card",i.innerHTML=`
    <img
      src="${e.image1x}"
      srcset="${e.image1x} 1x, ${e.image2x} 2x"
      alt="${e.alt}"
      class="project-img">
    <p class="project-tech">${e.tech}</p>
    <div class="link-visit">
      <h3 class="project-title">${e.title}</h3>
      <a href="${e.link}" class="project-btn" target="_blank" rel="noopener noreferrer">
        VISIT
        <svg class="icon-project" width="18" height="18">
          <use href="${S}#arrow-visit"></use>
        </svg>
      </a>
    </div>
  `,setTimeout(()=>i.classList.add("show"),10),i},w=()=>{const e=l.slice(n,n+d),i=[];return e.forEach(o=>{const r=f(o);j.appendChild(r),i.push(r)}),n+=d,n>=l.length&&(p.style.display="none"),i},x=e=>{e.length>0&&setTimeout(()=>{e[0].scrollIntoView({behavior:"smooth",block:"start"})},200)},u=(e=!1)=>{const i=w();e||x(i)};u(!0);p.addEventListener("click",()=>u());m.use([h,v]);const y=document.querySelector("#reviews-container"),b=document.querySelector(".error-message"),I=document.querySelector(".swiper-btns");g.defaults.baseURL="https://portfolio-js.b.goit.study/api";document.addEventListener("DOMContentLoaded",N);const T=new m(".swiper",{keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},breakpoints:{100:{slidesPerView:1,spaceBetween:20},768:{slidesPerView:1,spaceBetween:30},1280:{slidesPerView:2,spaceBetween:32}}});async function k(){try{const{data:e}=await g.get("/reviews");return e}catch{console.log("Error fetching reviews"),O(),R()}}function B(e){const i=e.map(({author:o,avatar_url:r,review:t})=>`
          <li class="swiper-slide libox">
            <div class="review-card">
            <p class="review-text">${t}</p>
            <div class="review-info">
              <img src="${r}" alt="${o}" class="review-avatar" />
              <h3 class="review-author">${o}</h3>
              </div>

            </div>
          </li>
        `).join("");y.insertAdjacentHTML("beforeend",i),T.update()}async function N(){const e=await k();e&&B(e)}function O(){b.classList.remove("visually-hidden")}function R(){I.classList.add("visually-hidden")}document.addEventListener("DOMContentLoaded",()=>{const e=document.getElementById("menuBtn"),i=document.getElementById("closeBtn"),o=document.getElementById("mobileMenu"),r=document.querySelectorAll(".mobile-link"),t=()=>{o.classList.remove("hidden"),o.classList.add("show"),document.body.classList.add("no-scroll")},s=()=>{o.classList.remove("show"),setTimeout(()=>{o.classList.add("hidden")},300),document.body.classList.remove("no-scroll")};e.addEventListener("click",t),i.addEventListener("click",s),r.forEach(c=>c.addEventListener("click",s))});const a=document.getElementById("theme-toggle");localStorage.getItem("theme")==="dark"&&(document.body.classList.add("dark"),document.body.classList.remove("light"),a.checked=!0);a.addEventListener("change",()=>{a.checked?(document.body.classList.add("dark"),document.body.classList.remove("light"),localStorage.setItem("theme","dark")):(document.body.classList.add("light"),document.body.classList.remove("dark"),localStorage.setItem("theme","light"))});
//# sourceMappingURL=index.js.map
